import {
  Banknote,
  Building2,
  CircleDollarSign,
  Coins,
  CreditCard,
  Globe,
  HandCoins,
  Landmark,
  PiggyBank,
  Receipt,
  Smartphone,
  Store,
  TrendingUp,
  Vault,
  Wallet,
  WalletCards,
  type LucideIcon,
} from "lucide-react";

export const ACCOUNT_ICON_NAMES = [
  "wallet",
  "credit_card",
  "bank",
  "savings",
  "cash",
  "coins",
  "dollar",
  "building",
  "hand_coins",
  "receipt",
  "wallet_cards",
  "vault",
  "smartphone",
  "globe",
  "store",
  "trending_up",
] as const;

export type AccountIcon = (typeof ACCOUNT_ICON_NAMES)[number];

export const ACCOUNT_ICONS: Record<AccountIcon, LucideIcon> = {
  wallet: Wallet,
  credit_card: CreditCard,
  bank: Landmark,
  savings: PiggyBank,
  cash: Banknote,
  coins: Coins,
  dollar: CircleDollarSign,
  building: Building2,
  hand_coins: HandCoins,
  receipt: Receipt,
  wallet_cards: WalletCards,
  vault: Vault,
  smartphone: Smartphone,
  globe: Globe,
  store: Store,
  trending_up: TrendingUp,
};
